name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # Este es el tipo de release para un proyecto Node.js.
          # Actualizará automáticamente el package.json y el CHANGELOG.md
          release-type: node
          # Opcional: si tu package.json no está en la raíz
          # package-name: 'cubo-pos-sdk-web'
